import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppoloWrapper from "@/providers/AppoloWrapper";
import NextAuthWrapper from "@/providers/NextAuthWrapper";
import ToastProvider from "@/providers/ToastProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-5">
        <NextAuthWrapper>
          <AppoloWrapper>
            <ToastProvider>
              <Header />
              {children}
              <Footer />
            </ToastProvider>
          </AppoloWrapper>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
